version: '3.2'

services:
  app:
    build:
      context: ./app
    environment:
      - TZ=JST-9
    volumes:
      - type: bind
        source: ../
        target: /home/app
    command: sh -c "yarn start"
    networks:
      - docknet
    ports:
      - "3000:3000"


networks:
  docknet:
    external: true
